# Generated by Django 4.0.4 on 2022-05-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='Author',
            new_name='author',
        ),
    ]
